/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Thu Oct 20 11:44:01 2016
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QGraphicsView>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSpinBox>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QCheckBox *checkBox_ContinuousRecog;
    QPushButton *pushButton_Save;
    QPushButton *pushButton_Open;
    QPushButton *pushButton_Enroll;
    QPushButton *pushButton_Close;
    QPushButton *pushButton_Stop;
    QGraphicsView *graphicsView_RightEye;
    QGraphicsView *graphicsView_RightEyeDistance;
    QGraphicsView *graphicsView_LeftEye;
    QGraphicsView *graphicsView_LeftEyeDistance;
    QPushButton *pushButton_Recog;
    QCheckBox *checkBox_PopUpMatchWindow;
    QComboBox *comboBox_SerialNumbers;
    QLabel *label_ModelName;
    QCheckBox *checkBox_AutoStart;
    QLabel *label_10;
    QLabel *label_ActionEvent;
    QLabel *label_11;
    QLabel *label_EMAEvent;
    QLabel *label_17;
    QLabel *label_FirmwareRev;
    QLabel *label_MirlinLevel;
    QLabel *label_24;
    QLabel *label_IndColor;
    QLabel *label_33;
    QLabel *label_15;
    QLabel *label_42;
    QLabel *label_5;
    QLabel *label_RightHD;
    QLabel *label_RightEyeDistance;
    QLabel *label_9;
    QLabel *label_LeftArea;
    QLabel *label_LeftHD;
    QLabel *label_RightIrisSize;
    QLabel *label_7;
    QLabel *label_RightArea;
    QLabel *label_LeftEyeDistance;
    QLabel *label_LeftIrisSize;
    QLabel *label_16;
    QLabel *label_43;
    QLabel *label_IPD;
    QLabel *label_8;
    QLabel *label_6;
    QLabel *label_Name;
    QLabel *label_44;
    QLabel *label_46;
    QLabel *label_Result;
    QWidget *tab_3;
    QGraphicsView *graphicsView_Face;
    QWidget *tab_2;
    QGroupBox *groupBox_2;
    QCheckBox *checkBox_Display;
    QLabel *label_12;
    QSpinBox *spinBox_DisplayRate;
    QLabel *label_27;
    QCheckBox *checkBox_DisplayIrisInLive;
    QGroupBox *groupBox_3;
    QLabel *label_14;
    QLabel *label_19;
    QLabel *label_18;
    QSpinBox *spinBox_TargetBrightness;
    QDoubleSpinBox *doubleSpinBox_MaxXYMovement;
    QLabel *label_22;
    QLabel *label_20;
    QDoubleSpinBox *doubleSpinBox_MaxZMovement;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *label_34;
    QSpinBox *spinBox_EnrolInDepthOfField;
    QLabel *label_37;
    QSpinBox *spinBox_EnrolOutDepthOfField;
    QLabel *label_39;
    QSpinBox *spinBox_RecogInDepthOfField;
    QLabel *label_40;
    QLabel *label_38;
    QSpinBox *spinBox_RecogOutDepthOfField;
    QGroupBox *groupBox_4;
    QCheckBox *checkBox_AutoSave;
    QCheckBox *checkBox_Inch;
    QLabel *label_25;
    QLabel *label_26;
    QSpinBox *spinBox_Interval;
    QLabel *label_28;
    QLabel *label_29;
    QSpinBox *spinBox_Red;
    QLabel *label_30;
    QSpinBox *spinBox_BrightGreen;
    QSpinBox *spinBox_Green;
    QSpinBox *spinBox_Blue;
    QLabel *label_31;
    QLabel *label_32;
    QCheckBox *checkBox_UsePSD;
    QGroupBox *groupBox_6;
    QLabel *label_13;
    QDoubleSpinBox *doubleSpinBox_HDThreshold;
    QGroupBox *groupBox_7;
    QLabel *label_35;
    QCheckBox *checkBox_EnableIndicatorEvent;
    QCheckBox *checkBox_EnableVocalCues;
    QSpinBox *spinBox_VocalCueFirstTimeInterval;
    QSpinBox *spinBox_VocalCueNextTimeInterval;
    QLabel *label_36;
    QGroupBox *groupBox_8;
    QSpinBox *spinBox_MaxFrameDiffInEitherEyeMode;
    QLabel *label_50;
    QLabel *label_49;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QGroupBox *groupBox_14;
    QRadioButton *radioButton_RecogBothEyes;
    QRadioButton *radioButton_RecogEitherEye;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1360, 721);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 1361, 701));
        QPalette palette;
        QBrush brush(QColor(235, 235, 235, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        tabWidget->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("Arial"));
        font.setPointSize(16);
        font.setItalic(false);
        tabWidget->setFont(font);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        checkBox_ContinuousRecog = new QCheckBox(tab);
        checkBox_ContinuousRecog->setObjectName(QString::fromUtf8("checkBox_ContinuousRecog"));
        checkBox_ContinuousRecog->setGeometry(QRect(810, 600, 191, 31));
        QPalette palette1;
        QBrush brush2(QColor(46, 78, 221, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        QBrush brush3(QColor(120, 120, 120, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_ContinuousRecog->setPalette(palette1);
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial"));
        font1.setPointSize(14);
        font1.setItalic(true);
        checkBox_ContinuousRecog->setFont(font1);
        checkBox_ContinuousRecog->setChecked(true);
        pushButton_Save = new QPushButton(tab);
        pushButton_Save->setObjectName(QString::fromUtf8("pushButton_Save"));
        pushButton_Save->setGeometry(QRect(570, 610, 101, 51));
        QPalette palette2;
        QBrush brush4(QColor(0, 0, 127, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Save->setPalette(palette2);
        QFont font2;
        font2.setFamily(QString::fromUtf8("Calibri"));
        font2.setPointSize(20);
        font2.setBold(false);
        font2.setWeight(50);
        pushButton_Save->setFont(font2);
        pushButton_Open = new QPushButton(tab);
        pushButton_Open->setObjectName(QString::fromUtf8("pushButton_Open"));
        pushButton_Open->setGeometry(QRect(10, 610, 91, 51));
        QPalette palette3;
        QBrush brush5(QColor(0, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Open->setPalette(palette3);
        pushButton_Open->setFont(font2);
        pushButton_Enroll = new QPushButton(tab);
        pushButton_Enroll->setObjectName(QString::fromUtf8("pushButton_Enroll"));
        pushButton_Enroll->setGeometry(QRect(210, 610, 111, 51));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush5);
        QBrush brush6(QColor(170, 0, 127, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Enroll->setPalette(palette4);
        QFont font3;
        font3.setFamily(QString::fromUtf8("Calibri"));
        font3.setPointSize(22);
        font3.setBold(true);
        font3.setWeight(75);
        pushButton_Enroll->setFont(font3);
        pushButton_Close = new QPushButton(tab);
        pushButton_Close->setObjectName(QString::fromUtf8("pushButton_Close"));
        pushButton_Close->setGeometry(QRect(110, 610, 91, 51));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Close->setPalette(palette5);
        pushButton_Close->setFont(font2);
        pushButton_Stop = new QPushButton(tab);
        pushButton_Stop->setObjectName(QString::fromUtf8("pushButton_Stop"));
        pushButton_Stop->setGeometry(QRect(450, 610, 111, 51));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Stop->setPalette(palette6);
        pushButton_Stop->setFont(font2);
        graphicsView_RightEye = new QGraphicsView(tab);
        graphicsView_RightEye->setObjectName(QString::fromUtf8("graphicsView_RightEye"));
        graphicsView_RightEye->setGeometry(QRect(10, 60, 644, 484));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(graphicsView_RightEye->sizePolicy().hasHeightForWidth());
        graphicsView_RightEye->setSizePolicy(sizePolicy);
        graphicsView_RightEye->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_RightEye->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_RightEyeDistance = new QGraphicsView(tab);
        graphicsView_RightEyeDistance->setObjectName(QString::fromUtf8("graphicsView_RightEyeDistance"));
        graphicsView_RightEyeDistance->setGeometry(QRect(654, 60, 19, 484));
        sizePolicy.setHeightForWidth(graphicsView_RightEyeDistance->sizePolicy().hasHeightForWidth());
        graphicsView_RightEyeDistance->setSizePolicy(sizePolicy);
        graphicsView_RightEyeDistance->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_RightEyeDistance->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_LeftEye = new QGraphicsView(tab);
        graphicsView_LeftEye->setObjectName(QString::fromUtf8("graphicsView_LeftEye"));
        graphicsView_LeftEye->setGeometry(QRect(695, 60, 644, 484));
        sizePolicy.setHeightForWidth(graphicsView_LeftEye->sizePolicy().hasHeightForWidth());
        graphicsView_LeftEye->setSizePolicy(sizePolicy);
        graphicsView_LeftEye->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_LeftEye->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_LeftEyeDistance = new QGraphicsView(tab);
        graphicsView_LeftEyeDistance->setObjectName(QString::fromUtf8("graphicsView_LeftEyeDistance"));
        graphicsView_LeftEyeDistance->setGeometry(QRect(676, 60, 19, 484));
        sizePolicy.setHeightForWidth(graphicsView_LeftEyeDistance->sizePolicy().hasHeightForWidth());
        graphicsView_LeftEyeDistance->setSizePolicy(sizePolicy);
        graphicsView_LeftEyeDistance->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsView_LeftEyeDistance->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        pushButton_Recog = new QPushButton(tab);
        pushButton_Recog->setObjectName(QString::fromUtf8("pushButton_Recog"));
        pushButton_Recog->setGeometry(QRect(330, 610, 111, 51));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        pushButton_Recog->setPalette(palette7);
        pushButton_Recog->setFont(font3);
        checkBox_PopUpMatchWindow = new QCheckBox(tab);
        checkBox_PopUpMatchWindow->setObjectName(QString::fromUtf8("checkBox_PopUpMatchWindow"));
        checkBox_PopUpMatchWindow->setGeometry(QRect(680, 630, 231, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_PopUpMatchWindow->setPalette(palette8);
        checkBox_PopUpMatchWindow->setFont(font1);
        checkBox_PopUpMatchWindow->setChecked(false);
        comboBox_SerialNumbers = new QComboBox(tab);
        comboBox_SerialNumbers->setObjectName(QString::fromUtf8("comboBox_SerialNumbers"));
        comboBox_SerialNumbers->setGeometry(QRect(1000, 20, 211, 31));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Arial"));
        font4.setPointSize(16);
        comboBox_SerialNumbers->setFont(font4);
        label_ModelName = new QLabel(tab);
        label_ModelName->setObjectName(QString::fromUtf8("label_ModelName"));
        label_ModelName->setGeometry(QRect(1220, 20, 111, 31));
        QPalette palette9;
        QBrush brush7(QColor(255, 85, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_ModelName->setPalette(palette9);
        QFont font5;
        font5.setFamily(QString::fromUtf8("Arial"));
        font5.setPointSize(18);
        font5.setBold(true);
        font5.setWeight(75);
        label_ModelName->setFont(font5);
        checkBox_AutoStart = new QCheckBox(tab);
        checkBox_AutoStart->setObjectName(QString::fromUtf8("checkBox_AutoStart"));
        checkBox_AutoStart->setGeometry(QRect(680, 600, 131, 31));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_AutoStart->setPalette(palette10);
        checkBox_AutoStart->setFont(font1);
        checkBox_AutoStart->setChecked(true);
        label_10 = new QLabel(tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(40, 10, 131, 41));
        QPalette palette11;
        QBrush brush8(QColor(100, 100, 100, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_10->setPalette(palette11);
        label_10->setFont(font1);
        label_ActionEvent = new QLabel(tab);
        label_ActionEvent->setObjectName(QString::fromUtf8("label_ActionEvent"));
        label_ActionEvent->setGeometry(QRect(170, 10, 271, 41));
        QPalette palette12;
        QBrush brush9(QColor(170, 0, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_ActionEvent->setPalette(palette12);
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial"));
        font6.setPointSize(14);
        font6.setBold(false);
        font6.setItalic(false);
        font6.setWeight(50);
        label_ActionEvent->setFont(font6);
        label_11 = new QLabel(tab);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(460, 10, 151, 41));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_11->setPalette(palette13);
        label_11->setFont(font1);
        label_EMAEvent = new QLabel(tab);
        label_EMAEvent->setObjectName(QString::fromUtf8("label_EMAEvent"));
        label_EMAEvent->setGeometry(QRect(620, 10, 351, 41));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_EMAEvent->setPalette(palette14);
        label_EMAEvent->setFont(font6);
        label_17 = new QLabel(tab);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1050, 630, 101, 31));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_17->setPalette(palette15);
        label_17->setFont(font);
        label_FirmwareRev = new QLabel(tab);
        label_FirmwareRev->setObjectName(QString::fromUtf8("label_FirmwareRev"));
        label_FirmwareRev->setGeometry(QRect(1150, 630, 81, 31));
        QPalette palette16;
        QBrush brush10(QColor(129, 129, 129, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_FirmwareRev->setPalette(palette16);
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial"));
        font7.setPointSize(16);
        font7.setItalic(true);
        label_FirmwareRev->setFont(font7);
        label_MirlinLevel = new QLabel(tab);
        label_MirlinLevel->setObjectName(QString::fromUtf8("label_MirlinLevel"));
        label_MirlinLevel->setGeometry(QRect(990, 630, 41, 31));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_MirlinLevel->setPalette(palette17);
        label_MirlinLevel->setFont(font7);
        label_24 = new QLabel(tab);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(920, 630, 61, 31));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_24->setPalette(palette18);
        label_24->setFont(font);
        label_IndColor = new QLabel(tab);
        label_IndColor->setObjectName(QString::fromUtf8("label_IndColor"));
        label_IndColor->setGeometry(QRect(1150, 600, 71, 31));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_IndColor->setPalette(palette19);
        label_IndColor->setFont(font7);
        label_33 = new QLabel(tab);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(1050, 600, 91, 31));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_33->setPalette(palette20);
        label_33->setFont(font);
        label_15 = new QLabel(tab);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(210, 576, 21, 21));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_15->setPalette(palette21);
        QFont font8;
        font8.setFamily(QString::fromUtf8("Arial"));
        font8.setPointSize(14);
        font8.setItalic(false);
        label_15->setFont(font8);
        label_42 = new QLabel(tab);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(190, 550, 41, 21));
        QPalette palette22;
        QBrush brush11(QColor(0, 0, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_42->setPalette(palette22);
        QFont font9;
        font9.setFamily(QString::fromUtf8("Arial"));
        font9.setPointSize(12);
        font9.setBold(true);
        font9.setWeight(75);
        label_42->setFont(font9);
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 576, 91, 21));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_5->setPalette(palette23);
        label_5->setFont(font8);
        label_RightHD = new QLabel(tab);
        label_RightHD->setObjectName(QString::fromUtf8("label_RightHD"));
        label_RightHD->setGeometry(QRect(110, 550, 61, 21));
        QPalette palette24;
        QBrush brush12(QColor(255, 0, 0, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_RightHD->setPalette(palette24);
        QFont font10;
        font10.setFamily(QString::fromUtf8("Arial"));
        font10.setPointSize(14);
        label_RightHD->setFont(font10);
        label_RightEyeDistance = new QLabel(tab);
        label_RightEyeDistance->setObjectName(QString::fromUtf8("label_RightEyeDistance"));
        label_RightEyeDistance->setGeometry(QRect(240, 576, 71, 21));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_RightEyeDistance->setPalette(palette25);
        label_RightEyeDistance->setFont(font1);
        label_9 = new QLabel(tab);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(1088, 550, 31, 21));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_9->setPalette(palette26);
        QFont font11;
        font11.setFamily(QString::fromUtf8("Arial"));
        font11.setPointSize(14);
        font11.setBold(false);
        font11.setWeight(50);
        label_9->setFont(font11);
        label_LeftArea = new QLabel(tab);
        label_LeftArea->setObjectName(QString::fromUtf8("label_LeftArea"));
        label_LeftArea->setGeometry(QRect(1260, 550, 61, 21));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_LeftArea->setPalette(palette27);
        label_LeftArea->setFont(font10);
        label_LeftHD = new QLabel(tab);
        label_LeftHD->setObjectName(QString::fromUtf8("label_LeftHD"));
        label_LeftHD->setGeometry(QRect(1130, 550, 61, 21));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_LeftHD->setPalette(palette28);
        label_LeftHD->setFont(font10);
        label_RightIrisSize = new QLabel(tab);
        label_RightIrisSize->setObjectName(QString::fromUtf8("label_RightIrisSize"));
        label_RightIrisSize->setGeometry(QRect(110, 576, 41, 21));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_RightIrisSize->setPalette(palette29);
        label_RightIrisSize->setFont(font10);
        label_7 = new QLabel(tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(320, 550, 41, 21));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_7->setPalette(palette30);
        label_7->setFont(font10);
        label_RightArea = new QLabel(tab);
        label_RightArea->setObjectName(QString::fromUtf8("label_RightArea"));
        label_RightArea->setGeometry(QRect(240, 550, 61, 21));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_RightArea->setPalette(palette31);
        label_RightArea->setFont(font10);
        label_LeftEyeDistance = new QLabel(tab);
        label_LeftEyeDistance->setObjectName(QString::fromUtf8("label_LeftEyeDistance"));
        label_LeftEyeDistance->setGeometry(QRect(1260, 576, 71, 21));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_LeftEyeDistance->setPalette(palette32);
        label_LeftEyeDistance->setFont(font1);
        label_LeftIrisSize = new QLabel(tab);
        label_LeftIrisSize->setObjectName(QString::fromUtf8("label_LeftIrisSize"));
        label_LeftIrisSize->setGeometry(QRect(1130, 576, 41, 21));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_LeftIrisSize->setPalette(palette33);
        label_LeftIrisSize->setFont(font10);
        label_16 = new QLabel(tab);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(1230, 576, 21, 21));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_16->setPalette(palette34);
        label_16->setFont(font8);
        label_43 = new QLabel(tab);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(1207, 550, 41, 21));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_43->setPalette(palette35);
        label_43->setFont(font9);
        label_IPD = new QLabel(tab);
        label_IPD->setObjectName(QString::fromUtf8("label_IPD"));
        label_IPD->setGeometry(QRect(360, 550, 91, 21));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_IPD->setPalette(palette36);
        label_IPD->setFont(font10);
        label_8 = new QLabel(tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(70, 550, 31, 21));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_8->setPalette(palette37);
        label_8->setFont(font11);
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(1040, 576, 81, 21));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_6->setPalette(palette38);
        label_6->setFont(font10);
        label_Name = new QLabel(tab);
        label_Name->setObjectName(QString::fromUtf8("label_Name"));
        label_Name->setGeometry(QRect(760, 550, 251, 21));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_Name->setPalette(palette39);
        QFont font12;
        font12.setFamily(QString::fromUtf8("Ubuntu"));
        font12.setPointSize(13);
        font12.setBold(true);
        font12.setItalic(false);
        font12.setWeight(75);
        label_Name->setFont(font12);
        label_Name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_44 = new QLabel(tab);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(690, 550, 61, 21));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_44->setPalette(palette40);
        QFont font13;
        font13.setFamily(QString::fromUtf8("Ubuntu"));
        font13.setPointSize(12);
        font13.setBold(true);
        font13.setItalic(true);
        font13.setWeight(75);
        label_44->setFont(font13);
        label_46 = new QLabel(tab);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(690, 576, 61, 21));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette41.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette41.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_46->setPalette(palette41);
        label_46->setFont(font13);
        label_Result = new QLabel(tab);
        label_Result->setObjectName(QString::fromUtf8("label_Result"));
        label_Result->setGeometry(QRect(760, 575, 251, 21));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette42.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette42.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_Result->setPalette(palette42);
        label_Result->setFont(font12);
        label_Result->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        graphicsView_Face = new QGraphicsView(tab_3);
        graphicsView_Face->setObjectName(QString::fromUtf8("graphicsView_Face"));
        graphicsView_Face->setGeometry(QRect(290, 0, 724, 701));
        tabWidget->addTab(tab_3, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        groupBox_2 = new QGroupBox(tab_2);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(30, 10, 381, 161));
        checkBox_Display = new QCheckBox(groupBox_2);
        checkBox_Display->setObjectName(QString::fromUtf8("checkBox_Display"));
        checkBox_Display->setGeometry(QRect(40, 30, 101, 51));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_Display->setPalette(palette43);
        checkBox_Display->setFont(font7);
        checkBox_Display->setChecked(false);
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(150, 30, 61, 51));
        QPalette palette44;
        QBrush brush13(QColor(0, 85, 255, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_12->setPalette(palette44);
        label_12->setFont(font4);
        spinBox_DisplayRate = new QSpinBox(groupBox_2);
        spinBox_DisplayRate->setObjectName(QString::fromUtf8("spinBox_DisplayRate"));
        spinBox_DisplayRate->setGeometry(QRect(220, 30, 61, 51));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette45.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette45.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette45.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette45.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette45.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_DisplayRate->setPalette(palette45);
        spinBox_DisplayRate->setFont(font4);
        spinBox_DisplayRate->setMinimum(1);
        spinBox_DisplayRate->setMaximum(30);
        label_27 = new QLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(290, 30, 71, 51));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_27->setPalette(palette46);
        label_27->setFont(font4);
        checkBox_DisplayIrisInLive = new QCheckBox(groupBox_2);
        checkBox_DisplayIrisInLive->setObjectName(QString::fromUtf8("checkBox_DisplayIrisInLive"));
        checkBox_DisplayIrisInLive->setGeometry(QRect(40, 80, 201, 51));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette47.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette47.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_DisplayIrisInLive->setPalette(palette47);
        checkBox_DisplayIrisInLive->setFont(font7);
        checkBox_DisplayIrisInLive->setChecked(true);
        groupBox_3 = new QGroupBox(tab_2);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(440, 10, 391, 351));
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(20, 90, 191, 31));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette48.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette48.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_14->setPalette(palette48);
        label_14->setFont(font4);
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(330, 100, 41, 31));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette49.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette49.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_19->setPalette(palette49);
        label_19->setFont(font4);
        label_18 = new QLabel(groupBox_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(30, 30, 181, 51));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette50.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette50.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_18->setPalette(palette50);
        label_18->setFont(font4);
        spinBox_TargetBrightness = new QSpinBox(groupBox_3);
        spinBox_TargetBrightness->setObjectName(QString::fromUtf8("spinBox_TargetBrightness"));
        spinBox_TargetBrightness->setGeometry(QRect(240, 30, 81, 51));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette51.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette51.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette51.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette51.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette51.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_TargetBrightness->setPalette(palette51);
        spinBox_TargetBrightness->setFont(font4);
        spinBox_TargetBrightness->setMinimum(80);
        spinBox_TargetBrightness->setMaximum(200);
        spinBox_TargetBrightness->setSingleStep(5);
        spinBox_TargetBrightness->setValue(130);
        doubleSpinBox_MaxXYMovement = new QDoubleSpinBox(groupBox_3);
        doubleSpinBox_MaxXYMovement->setObjectName(QString::fromUtf8("doubleSpinBox_MaxXYMovement"));
        doubleSpinBox_MaxXYMovement->setGeometry(QRect(240, 90, 81, 51));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette52.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette52.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        doubleSpinBox_MaxXYMovement->setPalette(palette52);
        doubleSpinBox_MaxXYMovement->setFont(font4);
        doubleSpinBox_MaxXYMovement->setDecimals(1);
        doubleSpinBox_MaxXYMovement->setMaximum(4);
        doubleSpinBox_MaxXYMovement->setSingleStep(0.1);
        doubleSpinBox_MaxXYMovement->setValue(1.6);
        label_22 = new QLabel(groupBox_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(34, 110, 171, 41));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette53.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette53.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_22->setPalette(palette53);
        label_22->setFont(font4);
        label_20 = new QLabel(groupBox_3);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(30, 154, 201, 31));
        QPalette palette54;
        palette54.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette54.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette54.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_20->setPalette(palette54);
        label_20->setFont(font4);
        doubleSpinBox_MaxZMovement = new QDoubleSpinBox(groupBox_3);
        doubleSpinBox_MaxZMovement->setObjectName(QString::fromUtf8("doubleSpinBox_MaxZMovement"));
        doubleSpinBox_MaxZMovement->setGeometry(QRect(240, 154, 81, 51));
        QPalette palette55;
        palette55.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette55.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette55.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        doubleSpinBox_MaxZMovement->setPalette(palette55);
        doubleSpinBox_MaxZMovement->setFont(font4);
        doubleSpinBox_MaxZMovement->setDecimals(1);
        doubleSpinBox_MaxZMovement->setMaximum(20);
        doubleSpinBox_MaxZMovement->setSingleStep(0.5);
        doubleSpinBox_MaxZMovement->setValue(12);
        label_21 = new QLabel(groupBox_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(330, 164, 41, 31));
        QPalette palette56;
        palette56.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette56.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette56.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_21->setPalette(palette56);
        label_21->setFont(font4);
        label_23 = new QLabel(groupBox_3);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(34, 174, 171, 41));
        QPalette palette57;
        palette57.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette57.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette57.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_23->setPalette(palette57);
        label_23->setFont(font4);
        label_34 = new QLabel(groupBox_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(40, 220, 141, 31));
        QPalette palette58;
        palette58.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette58.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette58.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_34->setPalette(palette58);
        label_34->setFont(font4);
        spinBox_EnrolInDepthOfField = new QSpinBox(groupBox_3);
        spinBox_EnrolInDepthOfField->setObjectName(QString::fromUtf8("spinBox_EnrolInDepthOfField"));
        spinBox_EnrolInDepthOfField->setGeometry(QRect(149, 255, 61, 31));
        QPalette palette59;
        palette59.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette59.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette59.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette59.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette59.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette59.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_EnrolInDepthOfField->setPalette(palette59);
        spinBox_EnrolInDepthOfField->setFont(font4);
        spinBox_EnrolInDepthOfField->setMinimum(15);
        spinBox_EnrolInDepthOfField->setMaximum(20);
        spinBox_EnrolInDepthOfField->setSingleStep(5);
        spinBox_EnrolInDepthOfField->setValue(15);
        label_37 = new QLabel(groupBox_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(59, 255, 81, 31));
        QPalette palette60;
        palette60.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette60.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette60.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_37->setPalette(palette60);
        label_37->setFont(font4);
        spinBox_EnrolOutDepthOfField = new QSpinBox(groupBox_3);
        spinBox_EnrolOutDepthOfField->setObjectName(QString::fromUtf8("spinBox_EnrolOutDepthOfField"));
        spinBox_EnrolOutDepthOfField->setGeometry(QRect(275, 255, 61, 31));
        QPalette palette61;
        palette61.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette61.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette61.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette61.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette61.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette61.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_EnrolOutDepthOfField->setPalette(palette61);
        spinBox_EnrolOutDepthOfField->setFont(font4);
        spinBox_EnrolOutDepthOfField->setMinimum(15);
        spinBox_EnrolOutDepthOfField->setMaximum(20);
        spinBox_EnrolOutDepthOfField->setSingleStep(5);
        spinBox_EnrolOutDepthOfField->setValue(15);
        label_39 = new QLabel(groupBox_3);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(229, 255, 41, 31));
        QPalette palette62;
        palette62.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette62.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette62.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_39->setPalette(palette62);
        label_39->setFont(font4);
        spinBox_RecogInDepthOfField = new QSpinBox(groupBox_3);
        spinBox_RecogInDepthOfField->setObjectName(QString::fromUtf8("spinBox_RecogInDepthOfField"));
        spinBox_RecogInDepthOfField->setGeometry(QRect(150, 299, 61, 31));
        QPalette palette63;
        palette63.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette63.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette63.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette63.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette63.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette63.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_RecogInDepthOfField->setPalette(palette63);
        spinBox_RecogInDepthOfField->setFont(font4);
        spinBox_RecogInDepthOfField->setMinimum(15);
        spinBox_RecogInDepthOfField->setMaximum(35);
        spinBox_RecogInDepthOfField->setSingleStep(5);
        spinBox_RecogInDepthOfField->setValue(35);
        label_40 = new QLabel(groupBox_3);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(230, 299, 41, 31));
        QPalette palette64;
        palette64.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette64.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette64.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_40->setPalette(palette64);
        label_40->setFont(font4);
        label_38 = new QLabel(groupBox_3);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(51, 299, 91, 31));
        QPalette palette65;
        palette65.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette65.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette65.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_38->setPalette(palette65);
        label_38->setFont(font4);
        spinBox_RecogOutDepthOfField = new QSpinBox(groupBox_3);
        spinBox_RecogOutDepthOfField->setObjectName(QString::fromUtf8("spinBox_RecogOutDepthOfField"));
        spinBox_RecogOutDepthOfField->setGeometry(QRect(275, 299, 61, 31));
        QPalette palette66;
        palette66.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette66.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette66.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette66.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette66.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette66.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_RecogOutDepthOfField->setPalette(palette66);
        spinBox_RecogOutDepthOfField->setFont(font4);
        spinBox_RecogOutDepthOfField->setMinimum(15);
        spinBox_RecogOutDepthOfField->setMaximum(25);
        spinBox_RecogOutDepthOfField->setSingleStep(5);
        spinBox_RecogOutDepthOfField->setValue(25);
        groupBox_4 = new QGroupBox(tab_2);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(860, 10, 411, 351));
        checkBox_AutoSave = new QCheckBox(groupBox_4);
        checkBox_AutoSave->setObjectName(QString::fromUtf8("checkBox_AutoSave"));
        checkBox_AutoSave->setGeometry(QRect(30, 40, 141, 31));
        QPalette palette67;
        palette67.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette67.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette67.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_AutoSave->setPalette(palette67);
        checkBox_AutoSave->setFont(font7);
        checkBox_Inch = new QCheckBox(groupBox_4);
        checkBox_Inch->setObjectName(QString::fromUtf8("checkBox_Inch"));
        checkBox_Inch->setGeometry(QRect(210, 40, 71, 31));
        QPalette palette68;
        palette68.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette68.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette68.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_Inch->setPalette(palette68);
        checkBox_Inch->setFont(font7);
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(30, 80, 201, 31));
        QPalette palette69;
        palette69.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette69.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette69.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_25->setPalette(palette69);
        label_25->setFont(font4);
        label_26 = new QLabel(groupBox_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(30, 110, 191, 31));
        QPalette palette70;
        palette70.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette70.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette70.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_26->setPalette(palette70);
        label_26->setFont(font4);
        spinBox_Interval = new QSpinBox(groupBox_4);
        spinBox_Interval->setObjectName(QString::fromUtf8("spinBox_Interval"));
        spinBox_Interval->setGeometry(QRect(240, 90, 81, 51));
        QPalette palette71;
        palette71.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette71.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette71.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette71.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette71.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette71.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_Interval->setPalette(palette71);
        spinBox_Interval->setFont(font4);
        spinBox_Interval->setMinimum(1);
        spinBox_Interval->setMaximum(20);
        spinBox_Interval->setSingleStep(1);
        spinBox_Interval->setValue(1);
        label_28 = new QLabel(groupBox_4);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(210, 200, 71, 31));
        QPalette palette72;
        QBrush brush14(QColor(0, 170, 0, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette72.setBrush(QPalette::Active, QPalette::WindowText, brush14);
        palette72.setBrush(QPalette::Inactive, QPalette::WindowText, brush14);
        palette72.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_28->setPalette(palette72);
        label_28->setFont(font4);
        label_29 = new QLabel(groupBox_4);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(320, 200, 51, 31));
        QPalette palette73;
        palette73.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette73.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette73.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_29->setPalette(palette73);
        label_29->setFont(font4);
        spinBox_Red = new QSpinBox(groupBox_4);
        spinBox_Red->setObjectName(QString::fromUtf8("spinBox_Red"));
        spinBox_Red->setGeometry(QRect(20, 240, 71, 51));
        QPalette palette74;
        palette74.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette74.setBrush(QPalette::Active, QPalette::Text, brush12);
        palette74.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette74.setBrush(QPalette::Inactive, QPalette::Text, brush12);
        palette74.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette74.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_Red->setPalette(palette74);
        spinBox_Red->setFont(font4);
        spinBox_Red->setMinimum(20);
        spinBox_Red->setMaximum(255);
        spinBox_Red->setSingleStep(5);
        spinBox_Red->setValue(60);
        label_30 = new QLabel(groupBox_4);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(120, 200, 61, 31));
        QPalette palette75;
        palette75.setBrush(QPalette::Active, QPalette::WindowText, brush14);
        palette75.setBrush(QPalette::Inactive, QPalette::WindowText, brush14);
        palette75.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_30->setPalette(palette75);
        label_30->setFont(font4);
        spinBox_BrightGreen = new QSpinBox(groupBox_4);
        spinBox_BrightGreen->setObjectName(QString::fromUtf8("spinBox_BrightGreen"));
        spinBox_BrightGreen->setGeometry(QRect(210, 240, 71, 51));
        QPalette palette76;
        palette76.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette76.setBrush(QPalette::Active, QPalette::Text, brush14);
        palette76.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette76.setBrush(QPalette::Inactive, QPalette::Text, brush14);
        palette76.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette76.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_BrightGreen->setPalette(palette76);
        spinBox_BrightGreen->setFont(font4);
        spinBox_BrightGreen->setMinimum(20);
        spinBox_BrightGreen->setMaximum(255);
        spinBox_BrightGreen->setSingleStep(5);
        spinBox_BrightGreen->setValue(120);
        spinBox_Green = new QSpinBox(groupBox_4);
        spinBox_Green->setObjectName(QString::fromUtf8("spinBox_Green"));
        spinBox_Green->setGeometry(QRect(120, 240, 71, 51));
        QPalette palette77;
        palette77.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette77.setBrush(QPalette::Active, QPalette::Text, brush14);
        palette77.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette77.setBrush(QPalette::Inactive, QPalette::Text, brush14);
        palette77.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette77.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_Green->setPalette(palette77);
        spinBox_Green->setFont(font4);
        spinBox_Green->setMinimum(20);
        spinBox_Green->setMaximum(255);
        spinBox_Green->setSingleStep(5);
        spinBox_Green->setValue(60);
        spinBox_Blue = new QSpinBox(groupBox_4);
        spinBox_Blue->setObjectName(QString::fromUtf8("spinBox_Blue"));
        spinBox_Blue->setGeometry(QRect(310, 240, 71, 51));
        QPalette palette78;
        palette78.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette78.setBrush(QPalette::Active, QPalette::Text, brush11);
        palette78.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette78.setBrush(QPalette::Inactive, QPalette::Text, brush11);
        palette78.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette78.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_Blue->setPalette(palette78);
        spinBox_Blue->setFont(font4);
        spinBox_Blue->setMinimum(20);
        spinBox_Blue->setMaximum(255);
        spinBox_Blue->setSingleStep(5);
        spinBox_Blue->setValue(150);
        label_31 = new QLabel(groupBox_4);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(30, 200, 41, 31));
        QPalette palette79;
        palette79.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette79.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette79.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_31->setPalette(palette79);
        label_31->setFont(font4);
        label_32 = new QLabel(groupBox_4);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(30, 160, 301, 31));
        QPalette palette80;
        palette80.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette80.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette80.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_32->setPalette(palette80);
        label_32->setFont(font4);
        checkBox_UsePSD = new QCheckBox(groupBox_4);
        checkBox_UsePSD->setObjectName(QString::fromUtf8("checkBox_UsePSD"));
        checkBox_UsePSD->setGeometry(QRect(30, 310, 371, 31));
        QPalette palette81;
        palette81.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette81.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette81.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_UsePSD->setPalette(palette81);
        checkBox_UsePSD->setFont(font7);
        checkBox_UsePSD->setChecked(true);
        groupBox_6 = new QGroupBox(tab_2);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(30, 180, 381, 181));
        label_13 = new QLabel(groupBox_6);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(20, 50, 191, 51));
        QPalette palette82;
        palette82.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette82.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette82.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_13->setPalette(palette82);
        label_13->setFont(font4);
        doubleSpinBox_HDThreshold = new QDoubleSpinBox(groupBox_6);
        doubleSpinBox_HDThreshold->setObjectName(QString::fromUtf8("doubleSpinBox_HDThreshold"));
        doubleSpinBox_HDThreshold->setGeometry(QRect(250, 50, 81, 51));
        QPalette palette83;
        palette83.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette83.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette83.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        doubleSpinBox_HDThreshold->setPalette(palette83);
        doubleSpinBox_HDThreshold->setFont(font4);
        doubleSpinBox_HDThreshold->setDecimals(2);
        doubleSpinBox_HDThreshold->setMaximum(0.5);
        doubleSpinBox_HDThreshold->setSingleStep(0.01);
        doubleSpinBox_HDThreshold->setValue(0.15);
        groupBox_7 = new QGroupBox(tab_2);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(30, 370, 511, 291));
        label_35 = new QLabel(groupBox_7);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(30, 120, 351, 51));
        QPalette palette84;
        palette84.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette84.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette84.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_35->setPalette(palette84);
        label_35->setFont(font4);
        checkBox_EnableIndicatorEvent = new QCheckBox(groupBox_7);
        checkBox_EnableIndicatorEvent->setObjectName(QString::fromUtf8("checkBox_EnableIndicatorEvent"));
        checkBox_EnableIndicatorEvent->setGeometry(QRect(30, 40, 381, 41));
        QPalette palette85;
        palette85.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette85.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette85.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_EnableIndicatorEvent->setPalette(palette85);
        checkBox_EnableIndicatorEvent->setFont(font7);
        checkBox_EnableIndicatorEvent->setChecked(true);
        checkBox_EnableVocalCues = new QCheckBox(groupBox_7);
        checkBox_EnableVocalCues->setObjectName(QString::fromUtf8("checkBox_EnableVocalCues"));
        checkBox_EnableVocalCues->setGeometry(QRect(30, 80, 211, 41));
        QPalette palette86;
        palette86.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette86.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette86.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        checkBox_EnableVocalCues->setPalette(palette86);
        checkBox_EnableVocalCues->setFont(font7);
        checkBox_EnableVocalCues->setChecked(true);
        spinBox_VocalCueFirstTimeInterval = new QSpinBox(groupBox_7);
        spinBox_VocalCueFirstTimeInterval->setObjectName(QString::fromUtf8("spinBox_VocalCueFirstTimeInterval"));
        spinBox_VocalCueFirstTimeInterval->setGeometry(QRect(400, 120, 81, 51));
        QPalette palette87;
        palette87.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette87.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette87.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette87.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette87.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette87.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_VocalCueFirstTimeInterval->setPalette(palette87);
        spinBox_VocalCueFirstTimeInterval->setFont(font4);
        spinBox_VocalCueFirstTimeInterval->setMinimum(15);
        spinBox_VocalCueFirstTimeInterval->setMaximum(300);
        spinBox_VocalCueFirstTimeInterval->setSingleStep(1);
        spinBox_VocalCueFirstTimeInterval->setValue(75);
        spinBox_VocalCueNextTimeInterval = new QSpinBox(groupBox_7);
        spinBox_VocalCueNextTimeInterval->setObjectName(QString::fromUtf8("spinBox_VocalCueNextTimeInterval"));
        spinBox_VocalCueNextTimeInterval->setGeometry(QRect(400, 180, 81, 51));
        QPalette palette88;
        palette88.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette88.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette88.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette88.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette88.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette88.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_VocalCueNextTimeInterval->setPalette(palette88);
        spinBox_VocalCueNextTimeInterval->setFont(font4);
        spinBox_VocalCueNextTimeInterval->setMinimum(15);
        spinBox_VocalCueNextTimeInterval->setMaximum(300);
        spinBox_VocalCueNextTimeInterval->setSingleStep(1);
        spinBox_VocalCueNextTimeInterval->setValue(90);
        label_36 = new QLabel(groupBox_7);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(30, 180, 351, 51));
        QPalette palette89;
        palette89.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette89.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette89.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_36->setPalette(palette89);
        label_36->setFont(font4);
        groupBox_8 = new QGroupBox(tab_2);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(580, 370, 361, 291));
        QPalette palette90;
        QBrush brush15(QColor(85, 0, 127, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette90.setBrush(QPalette::Active, QPalette::WindowText, brush15);
        palette90.setBrush(QPalette::Inactive, QPalette::WindowText, brush15);
        palette90.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        groupBox_8->setPalette(palette90);
        QFont font14;
        font14.setFamily(QString::fromUtf8("Arial"));
        font14.setPointSize(16);
        font14.setBold(true);
        font14.setItalic(false);
        font14.setWeight(75);
        groupBox_8->setFont(font14);
        spinBox_MaxFrameDiffInEitherEyeMode = new QSpinBox(groupBox_8);
        spinBox_MaxFrameDiffInEitherEyeMode->setObjectName(QString::fromUtf8("spinBox_MaxFrameDiffInEitherEyeMode"));
        spinBox_MaxFrameDiffInEitherEyeMode->setGeometry(QRect(290, 130, 51, 51));
        QPalette palette91;
        palette91.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette91.setBrush(QPalette::Active, QPalette::Text, brush13);
        palette91.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette91.setBrush(QPalette::Inactive, QPalette::Text, brush13);
        palette91.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette91.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        spinBox_MaxFrameDiffInEitherEyeMode->setPalette(palette91);
        spinBox_MaxFrameDiffInEitherEyeMode->setFont(font);
        spinBox_MaxFrameDiffInEitherEyeMode->setMinimum(3);
        spinBox_MaxFrameDiffInEitherEyeMode->setMaximum(9);
        spinBox_MaxFrameDiffInEitherEyeMode->setSingleStep(1);
        spinBox_MaxFrameDiffInEitherEyeMode->setValue(3);
        label_50 = new QLabel(groupBox_8);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(30, 160, 241, 21));
        QPalette palette92;
        palette92.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette92.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette92.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_50->setPalette(palette92);
        label_50->setFont(font6);
        label_49 = new QLabel(groupBox_8);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(30, 130, 241, 21));
        QPalette palette93;
        palette93.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette93.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette93.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_49->setPalette(palette93);
        label_49->setFont(font6);
        label_51 = new QLabel(groupBox_8);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(30, 190, 241, 21));
        QPalette palette94;
        palette94.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette94.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette94.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_51->setPalette(palette94);
        QFont font15;
        font15.setFamily(QString::fromUtf8("Arial"));
        font15.setPointSize(12);
        font15.setBold(false);
        font15.setItalic(false);
        font15.setWeight(50);
        label_51->setFont(font15);
        label_52 = new QLabel(groupBox_8);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(30, 210, 241, 21));
        QPalette palette95;
        palette95.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette95.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette95.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_52->setPalette(palette95);
        label_52->setFont(font15);
        label_53 = new QLabel(groupBox_8);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(30, 230, 241, 21));
        QPalette palette96;
        palette96.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette96.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette96.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_53->setPalette(palette96);
        label_53->setFont(font15);
        groupBox_14 = new QGroupBox(groupBox_8);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(10, 40, 271, 61));
        QPalette palette97;
        palette97.setBrush(QPalette::Active, QPalette::WindowText, brush13);
        palette97.setBrush(QPalette::Inactive, QPalette::WindowText, brush13);
        palette97.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        groupBox_14->setPalette(palette97);
        QFont font16;
        font16.setPointSize(14);
        font16.setBold(false);
        font16.setWeight(50);
        groupBox_14->setFont(font16);
        radioButton_RecogBothEyes = new QRadioButton(groupBox_14);
        radioButton_RecogBothEyes->setObjectName(QString::fromUtf8("radioButton_RecogBothEyes"));
        radioButton_RecogBothEyes->setGeometry(QRect(10, 30, 101, 19));
        QPalette palette98;
        palette98.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette98.setBrush(QPalette::Active, QPalette::ButtonText, brush11);
        palette98.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette98.setBrush(QPalette::Inactive, QPalette::ButtonText, brush11);
        palette98.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette98.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        radioButton_RecogBothEyes->setPalette(palette98);
        QFont font17;
        font17.setFamily(QString::fromUtf8("Arial"));
        font17.setPointSize(12);
        font17.setBold(false);
        font17.setItalic(true);
        font17.setWeight(50);
        radioButton_RecogBothEyes->setFont(font17);
        radioButton_RecogBothEyes->setChecked(false);
        radioButton_RecogEitherEye = new QRadioButton(groupBox_14);
        radioButton_RecogEitherEye->setObjectName(QString::fromUtf8("radioButton_RecogEitherEye"));
        radioButton_RecogEitherEye->setGeometry(QRect(140, 30, 71, 19));
        QPalette palette99;
        palette99.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette99.setBrush(QPalette::Active, QPalette::ButtonText, brush11);
        palette99.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette99.setBrush(QPalette::Inactive, QPalette::ButtonText, brush11);
        palette99.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette99.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        radioButton_RecogEitherEye->setPalette(palette99);
        radioButton_RecogEitherEye->setFont(font17);
        radioButton_RecogEitherEye->setChecked(true);
        tabWidget->addTab(tab_2, QString());
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "CMIMIRDemo", 0, QApplication::UnicodeUTF8));
        checkBox_ContinuousRecog->setText(QApplication::translate("MainWindow", "Continuous Recog", 0, QApplication::UnicodeUTF8));
        pushButton_Save->setText(QApplication::translate("MainWindow", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_Open->setText(QApplication::translate("MainWindow", "Open", 0, QApplication::UnicodeUTF8));
        pushButton_Enroll->setText(QApplication::translate("MainWindow", "Enroll", 0, QApplication::UnicodeUTF8));
        pushButton_Close->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
        pushButton_Stop->setText(QApplication::translate("MainWindow", "Stop", 0, QApplication::UnicodeUTF8));
        pushButton_Recog->setText(QApplication::translate("MainWindow", "Recog", 0, QApplication::UnicodeUTF8));
        checkBox_PopUpMatchWindow->setText(QApplication::translate("MainWindow", "Pop up match window", 0, QApplication::UnicodeUTF8));
        label_ModelName->setText(QString());
        checkBox_AutoStart->setText(QApplication::translate("MainWindow", "Auto Start", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Buttons Event:", 0, QApplication::UnicodeUTF8));
        label_ActionEvent->setText(QString());
        label_11->setText(QApplication::translate("MainWindow", "EMA Event Type:", 0, QApplication::UnicodeUTF8));
        label_EMAEvent->setText(QString());
        label_17->setText(QApplication::translate("MainWindow", "Firmware:", 0, QApplication::UnicodeUTF8));
        label_FirmwareRev->setText(QString());
        label_MirlinLevel->setText(QString());
        label_24->setText(QApplication::translate("MainWindow", "Mirlin:", 0, QApplication::UnicodeUTF8));
        label_IndColor->setText(QString());
        label_33->setText(QApplication::translate("MainWindow", "Indicator:", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "D:", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("MainWindow", "Area:", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Right Size:", 0, QApplication::UnicodeUTF8));
        label_RightHD->setText(QString());
        label_RightEyeDistance->setText(QString());
        label_9->setText(QApplication::translate("MainWindow", "HD:", 0, QApplication::UnicodeUTF8));
        label_LeftArea->setText(QString());
        label_LeftHD->setText(QString());
        label_RightIrisSize->setText(QString());
        label_7->setText(QApplication::translate("MainWindow", "IPD:", 0, QApplication::UnicodeUTF8));
        label_RightArea->setText(QString());
        label_LeftEyeDistance->setText(QString());
        label_LeftIrisSize->setText(QString());
        label_16->setText(QApplication::translate("MainWindow", "D:", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("MainWindow", "Area:", 0, QApplication::UnicodeUTF8));
        label_IPD->setText(QString());
        label_8->setText(QApplication::translate("MainWindow", "HD:", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Left Size:", 0, QApplication::UnicodeUTF8));
        label_Name->setText(QString());
        label_44->setText(QApplication::translate("MainWindow", "Name:", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("MainWindow", "Result:", 0, QApplication::UnicodeUTF8));
        label_Result->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "     Main     ", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", " FaceImage", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", " Optimization && Display", 0, QApplication::UnicodeUTF8));
        checkBox_Display->setText(QApplication::translate("MainWindow", "Display", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "Every", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "frames", 0, QApplication::UnicodeUTF8));
        checkBox_DisplayIrisInLive->setText(QApplication::translate("MainWindow", "Display Iris in Live", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", " Image Capture Parameters", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Max XY Movement:", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "mm", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "Target Brightness:", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "(during 66.7 ms)", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "Max Z Movement:", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "mm", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "(during 66.7 ms)", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindow", "Depth of Field:", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindow", "Enroll In:", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("MainWindow", "Out:", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindow", "Out:", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("MainWindow", "Recog In:", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Capture Options ", 0, QApplication::UnicodeUTF8));
        checkBox_AutoSave->setText(QApplication::translate("MainWindow", "Auto Save", 0, QApplication::UnicodeUTF8));
        checkBox_Inch->setText(QApplication::translate("MainWindow", "inch", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "Continuous Recog", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "Time Interval (sec):", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "Bright", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "Blue", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "Green", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "Red", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindow", "Indicator Brightness(20 ~ 255):", 0, QApplication::UnicodeUTF8));
        checkBox_UsePSD->setText(QApplication::translate("MainWindow", "Enable EMA/EMB Proximity Sensor", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "MIRLIN SDK Options", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Hamming Distance\n"
"Threshold:", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "RGB color LED Indication and vocal cues", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindow", "Vocal cue first time interval (frames):", 0, QApplication::UnicodeUTF8));
        checkBox_EnableIndicatorEvent->setText(QApplication::translate("MainWindow", "Enable indicator color changed event", 0, QApplication::UnicodeUTF8));
        checkBox_EnableVocalCues->setText(QApplication::translate("MainWindow", "Enable vocal cues", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "Vocal cue next time interval (frames):", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Eye Capture mode", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("MainWindow", "Either Eye Mode (3 ~ 9):", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("MainWindow", "Max Frame Diff of 2 Eyes In", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("MainWindow", "3: Fastest Either Eye mode", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("MainWindow", "9: Try more to capture both eyes. ", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("MainWindow", "\"Either Eye\" only works in Recog", 0, QApplication::UnicodeUTF8));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "Recog Eye Capture mode:", 0, QApplication::UnicodeUTF8));
        radioButton_RecogBothEyes->setText(QApplication::translate("MainWindow", "Both Eyes", 0, QApplication::UnicodeUTF8));
        radioButton_RecogEitherEye->setText(QApplication::translate("MainWindow", "Either", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "     Options     ", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
